substitutions:
  name: basen-bms
  device_description: "Basen BMS test"
  # Interfaces GPIOs
  # uart_esp_1 (RS485 port)
  tx_pin_1: '22'
  rx_pin_1: '21'
  # uart_esp_2
  tx_pin_2: '33'
  rx_pin_2: '32'
  # uart_esp_3
  tx_pin_3: '35'
  rx_pin_3: '34'
  # canbus_esp32_can (CAN port)
  tx_pin_4: '27'
  rx_pin_4: '26'
  # canbus_mcp2515
  spi_mosi_pin: '12'
  spi_miso_pin: '5'
  spi_clk_pin: '18'
  mcp2515_cs_pin: '25'

esphome:
  name: ${name}
  friendly_name: ${name}
  comment: ${device_description}
  min_version: 2025.1.0

esp32:
  board: esp32dev
  framework:
    type: esp-idf

uart:
  - id: uart_esp_1
    tx_pin: ${tx_pin_1}
    rx_pin: ${rx_pin_1}
    baud_rate: 9600
    rx_buffer_size: 512

light:
  # https://esphome.io/components/light/esp32_rmt_led_strip
  # ESP Light used to see the inverter heartbeat
  # Internal : only specifying an id without a name will implicitly set this to true.
  - platform: esp32_rmt_led_strip
    id: esp_light
    rgb_order: GRB
    pin: 4
    num_leds: 1
    # rmt_channel: 0
    chipset: ws2812
    entity_category: config
    default_transition_length: 0ms

# +--------------------------------------+
# | LilyGo T-CAN485 related config       |
# +--------------------------------------+

output:
  # MAX13487E SHDN (enable RS485 chip)
  - platform: gpio
    id: RS485_SE
    pin:
      number: 19
      inverted: true # set HIGH level
  # MAX13487E RE (enable RS485 autodirection)
  - platform: gpio
    id: RS485_EN
    pin:
      number: 17
      inverted: true # set HIGH level
  # RS485 and CAN Boost power supply
  - platform: gpio
    id: CGQ_EN
    pin:
      number: 16
      inverted: true # set HIGH level
  # SN65HVD231DR RS PIN (CAN high speed mode)
  - platform: gpio
    id: CAN_SE
    pin:
      number: 23
      inverted: false # set LOW level

external_components:
  - source:
      type: local
      path: components

wifi:
  id: my_network
  networks:
    - ssid: !secret wifi_ssid
      bssid: !secret wifi_bssid
      password: !secret wifi_password
  domain: !secret domain
  ap:

ota:
  platform: esphome

logger:
  level: INFO
  baud_rate: 0

api:

basen_controller:
  - uart_id: uart_esp_1
    id: basen1
    throttle: 5s

basen_bms:
  - address: 0x01
    id: basen_bms1
    update_interval: 5s
  - address: 0x02
    id: basen_bms2
    update_interval: 5s
    
# +--------------------------------------+
# | Component entities                   |
# +--------------------------------------+

binary_sensor:
  - platform: basen_bms
    basen_bms_id: basen_bms1
    connected:
      name: "${name} 1 Connected"
  - platform: basen_bms
    basen_bms_id: basen_bms2
    connected:
      name: "${name} 2 Connected"

sensor:
  - platform: basen_bms
    basen_bms_id: basen_bms1
    voltage:
      name: "${name} 1 voltage"
    current:
      name: "${name} 1 current"
    power:
      name: "${name} 1 power"
    state_of_charge:
      name: "${name} 1 state of charge"
    state_of_health:
      name: "${name} 1 state of health"
    capacity:
      name: "${name} 1 capacity"
    cycles:
      name: "${name} 1 cycles"
    temperature1:
      name: "${name} 1 temperature 1"
    temperature2:
      name: "${name} 1 temperature 2"
    temperature3:
      name: "${name} 1 temperature 3"
    temperature4: 
      name: "${name} 1 temperature 4"
    temperature_mos:
      name: "${name} 1 temperature mos"
    temperature_ambient:
      name: "${name} 1 temperature ambient"
    avg_cell_voltage:
      name: "${name} 1 average cell voltage"
    min_cell_voltage:
      name: "${name} 1 minimum cell voltage"
    max_cell_voltage:
      name: "${name} 1 maximum cell voltage"
    min_cell_index:
      name: "${name} 1 minimum cell index"
    max_cell_index:
      name: "${name} 1 maximum cell index"
    delta_cell_voltage:
      name: "${name} 1 delta cell voltage"
    CELL_OV_Start:
      name: "${name} 1 CELL_OV_Start"
    CELL_OV_Delay:
      name: "${name} 1 CELL_OV_Delay"
    CELL_OV_Stop:
      name: "${name} 1 CELL_OV_Stop"
    CELL_UV_Start:
      name: "${name} 1 CELL_UV_Start"
    CELL_UV_Delay:
      name: "${name} 1 CELL_UV_Delay"
    CELL_UV_Stop:
      name: "${name} 1 CELL_UV_Stop"
    PACK_OV_Start:
      name: "${name} 1 PACK_OV_Start"
    PACK_OV_Delay:
      name: "${name} 1 PACK_OV_Delay"
    PACK_OV_Stop:
      name: "${name} 1 PACK_OV_Stop"
    PACK_UV_Start:
      name: "${name} 1 PACK_UV_Start"
    PACK_UV_Delay:
      name: "${name} 1 PACK_UV_Delay"
    PACK_UV_Stop:
      name: "${name} 1 PACK_UV_Stop"
    Const_Pack_V:
      name: "${name} 1 Const_Pack_V"
    Const_Current:
      name: "${name} 1 Const_Current"
    CHG_OC1_Start:
      name: "${name} 1 CHG_OC1_Start"
    CHG_OC1_Delay:
      name: "${name} 1 CHG_OC1_Delay"
    DISC_OC1_Start:
      name: "${name} 1 DISC_OC1_Start"
    DISC_OC1_Delay:
      name: "${name} 1 DISC_OC1_Delay"
    CHG_OC2_Start:
      name: "${name} 1 CHG_OC2_Start"
    CHG_OC2_Delay:
      name: "${name} 1 CHG_OC2_Delay"
    DISC_OC2_Start:
      name: "${name} 1 DISC_OC2_Start"
    DISC_OC2_Delay:
      name: "${name} 1 DISC_OC2_Delay"
    CHG_OT_START:
      name: "${name} 1 CHG_OT_START"
    CHG_OT_Delay:
      name: "${name} 1 CHG_OT_Delay"
    CHG_OT_STOP:
      name: "${name} 1 CHG_OT_STOP"
    DISC_OT_START:
      name: "${name} 1 DISC_OT_START"
    DISC_OT_Delay:
      name: "${name} 1 DISC_OT_Delay"
    DISC_OT_STOP:
      name: "${name} 1 DISC_OT_STOP"
    CHG_UT_START:
      name: "${name} 1 CHG_UT_START"
    CHG_UT_Delay:
      name: "${name} 1 CHG_UT_Delay"
    CHG_UT_STOP:
      name: "${name} 1 CHG_UT_STOP"
    DISC_UT_START:
      name: "${name} 1 DISC_UT_START"
    DISC_UT_Delay:
      name: "${name} 1 DISC_UT_Delay"
    DISC_UT_STOP:
      name: "${name} 1 DISC_UT_STOP"
    MOS_OT_START:
      name: "${name} 1 MOS_OT_START"
    MOS_OT_Delay:
      name: "${name} 1 MOS_OT_Delay"
    MOS_OT_STOP:
      name: "${name} 1 MOS_OT_STOP"
    ENV_OT_START:
      name: "${name} 1 ENV_OT_START"
    ENV_OT_Delay:
      name: "${name} 1 ENV_OT_Delay"
    ENV_OT_STOP:
      name: "${name} 1 ENV_OT_STOP"
    ENV_UT_START:
      name: "${name} 1 ENV_UT_START"
    ENV_UT_Delay:
      name: "${name} 1 ENV_UT_Delay"
    ENV_UT_STOP:
      name: "${name} 1 ENV_UT_STOP"
    Balance_Start_Vol:
      name: "${name} 1 Balance_Start_Vol"
    Balance_Start_Diff:
      name: "${name} 1 Balance_Start_Diff"
    Sleep_Cell_Volt:
      name: "${name} 1 Sleep_Cell_Volt"
    Shorts_Delay:
      name: "${name} 1 Shorts_Delay"
    Standby_Time:
      name: "${name} 1 Standby_Time"
    UV_OFF_Time:
      name: "${name} 1 UV_OFF_Time"
    LC_Style:
      name: "${name} 1 LC_Style"
    Sleep_Time:
      name: "${name} 1 Sleep_Time"

  - platform: basen_bms
    basen_bms_id: basen_bms2
    voltage:
      name: "${name} 2 voltage"
    current:
      name: "${name} 2 current"
    power:
      name: "${name} 2 power"
    state_of_charge:
      name: "${name} 2 state of charge"
    state_of_health:
      name: "${name} 2 state of health"
    capacity:
      name: "${name} 2 capacity"
    cycles:
      name: "${name} 2 cycles"
    temperature1:
      name: "${name} 2 temperature 1"
    temperature2:
      name: "${name} 2 temperature 2"
    temperature3:
      name: "${name} 2 temperature 3"
    temperature4: 
      name: "${name} 2 temperature 4"
    temperature_mos:
      name: "${name} 2 temperature mos"
    temperature_ambient:
      name: "${name} 2 temperature ambient"
    avg_cell_voltage:
      name: "${name} 2 average cell voltage"
    min_cell_voltage:
      name: "${name} 2 minimum cell voltage"
    max_cell_voltage:
      name: "${name} 2 maximum cell voltage"
    min_cell_index:
      name: "${name} 2 minimum cell index"
    max_cell_index:
      name: "${name} 2 maximum cell index"
    delta_cell_voltage:
      name: "${name} 2 delta cell voltage"
    CELL_OV_Start:
      name: "${name} 2 CELL_OV_Start"
    CELL_OV_Delay:
      name: "${name} 2 CELL_OV_Delay"
    CELL_OV_Stop:
      name: "${name} 2 CELL_OV_Stop"
    CELL_UV_Start:
      name: "${name} 2 CELL_UV_Start"
    CELL_UV_Delay:
      name: "${name} 2 CELL_UV_Delay"
    CELL_UV_Stop:
      name: "${name} 2 CELL_UV_Stop"
    PACK_OV_Start:
      name: "${name} 2 PACK_OV_Start"
    PACK_OV_Delay:
      name: "${name} 2 PACK_OV_Delay"
    PACK_OV_Stop:
      name: "${name} 2 PACK_OV_Stop"
    PACK_UV_Start:
      name: "${name} 2 PACK_UV_Start"
    PACK_UV_Delay:
      name: "${name} 2 PACK_UV_Delay"
    PACK_UV_Stop:
      name: "${name} 2 PACK_UV_Stop"
    Const_Pack_V:
      name: "${name} 2 Const_Pack_V"
    Const_Current:
      name: "${name} 2 Const_Current"
    CHG_OC1_Start:
      name: "${name} 2 CHG_OC1_Start"
    CHG_OC1_Delay:
      name: "${name} 2 CHG_OC1_Delay"
    DISC_OC1_Start:
      name: "${name} 2 DISC_OC1_Start"
    DISC_OC1_Delay:
      name: "${name} 2 DISC_OC1_Delay"
    CHG_OC2_Start:
      name: "${name} 2 CHG_OC2_Start"
    CHG_OC2_Delay:
      name: "${name} 2 CHG_OC2_Delay"
    DISC_OC2_Start:
      name: "${name} 2 DISC_OC2_Start"
    DISC_OC2_Delay:
      name: "${name} 2 DISC_OC2_Delay"
    CHG_OT_START:
      name: "${name} 2 CHG_OT_START"
    CHG_OT_Delay:
      name: "${name} 2 CHG_OT_Delay"
    CHG_OT_STOP:
      name: "${name} 2 CHG_OT_STOP"
    DISC_OT_START:
      name: "${name} 2 DISC_OT_START"
    DISC_OT_Delay:
      name: "${name} 2 DISC_OT_Delay"
    DISC_OT_STOP:
      name: "${name} 2 DISC_OT_STOP"
    CHG_UT_START:
      name: "${name} 2 CHG_UT_START"
    CHG_UT_Delay:
      name: "${name} 2 CHG_UT_Delay"
    CHG_UT_STOP:
      name: "${name} 2 CHG_UT_STOP"
    DISC_UT_START:
      name: "${name} 2 DISC_UT_START"
    DISC_UT_Delay:
      name: "${name} 2 DISC_UT_Delay"
    DISC_UT_STOP:
      name: "${name} 2 DISC_UT_STOP"
    MOS_OT_START:
      name: "${name} 2 MOS_OT_START"
    MOS_OT_Delay:
      name: "${name} 2 MOS_OT_Delay"
    MOS_OT_STOP:
      name: "${name} 2 MOS_OT_STOP"
    ENV_OT_START:
      name: "${name} 2 ENV_OT_START"
    ENV_OT_Delay:
      name: "${name} 2 ENV_OT_Delay"
    ENV_OT_STOP:
      name: "${name} 2 ENV_OT_STOP"
    ENV_UT_START:
      name: "${name} 2 ENV_UT_START"
    ENV_UT_Delay:
      name: "${name} 2 ENV_UT_Delay"
    ENV_UT_STOP:
      name: "${name} 2 ENV_UT_STOP"
    Balance_Start_Vol:
      name: "${name} 2 Balance_Start_Vol"
    Balance_Start_Diff:
      name: "${name} 2 Balance_Start_Diff"
    Sleep_Cell_Volt:
      name: "${name} 2 Sleep_Cell_Volt"
    Shorts_Delay:
      name: "${name} 2 Shorts_Delay"
    Standby_Time:
      name: "${name} 2 Standby_Time"
    UV_OFF_Time:
      name: "${name} 2 UV_OFF_Time"
    LC_Style:
      name: "${name} 2 LC_Style"
    Sleep_Time:
      name: "${name} 2 Sleep_Time"
      
  - platform: debug
    free:
      name: ${name} Heap free
      id: esp32_heap_free
    block:
      name: ${name} Heap max block
      id: esp32_heap_max_block
    loop_time:
      name: ${name} Loop time
      id: esp32_loop_time

text_sensor:
 - platform: basen_bms
   basen_bms_id: basen_bms1
   bms_version:
     id: bms_version1
     name: "${name} 1 BMS version"
   barcode:
     id: barcode1
     name: "${name} 1 BMS barcode"
   status_bitmask:
     id: status_bitmap1
     name: "${name} 1 Status bitmap"
   status:
     id: status1
     name: "${name} 1 Status"
 - platform: basen_bms
   basen_bms_id: basen_bms2
   bms_version:
     id: bms_version2
     name: "${name} 2 BMS version"
   barcode:
     id: barcode2
     name: "${name} 2 BMS barcode"
   status_bitmask:
     id: status_bitmap2
     name: "${name} 2 Status bitmap"
   status:
     id: status2
     name: "${name} 2 Status"

 - platform: debug
   device:
     name: ${name} Device info
     id: esp32_device_info
   reset_reason:
     name: ${name} Reset reason
     id: esp32_reset_reason
    
debug:
  update_interval: 5s
